### ISSUE TITLE
Bosh has problems unmounting persistent disk on stemcell update

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-community/jumpbox-boshrelease#26]
Every stemcell update we see this error:
```
  Started updating instance jumpbox > jumpbox/2cfe6e2f-f1b6-4d13-99c4-c5e11a3d0ee7 (0) (canary). Failed: Action Failed get_task: Task c712ed9f-aed3-4530-7de3-74fccb955350 result: Unmounting persistent disk: Running command: 'umount /dev/xvdf1', stdout: '', stderr: 'umount: /var/vcap/store: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
': exit status 1 (00:10:14)

Error 450001: Action Failed get_task: Task c712ed9f-aed3-4530-7de3-74fccb955350 result: Unmounting persistent disk: Running command: 'umount /dev/xvdf1', stdout: '', stderr: 'umount: /var/vcap/store: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))
': exit status 1

```

Could be with how we are symlinking the `/var/vcap/store` to be accessible as a persistent directory for each user. 
What are current best practices to provide easy access to persistent folders for users and how can the unmounting issue be fixed?

**Comment by geofffranks** [comment]
What files were open when you ran lsof?

Where were you updating the jumpbox boshrelease from? You'll need to do it from another location, while all users are logged out from the jumpbox.

**Comment by jhunt** [comment]
You cannot redeploy the jumpbox when people are on it, currently.  We could put a `stop` action that `wall`s about an impending shutdown, and then looks through `lsof` output and kills all processes that are using `/var/vcap/store`, but that would need to be configurable.  I personally like having the protection of not losing my running tmux sessions because someone wanted to upgrade a point release.
