### ISSUE TITLE
authorized_keys does not update for an existing user.

### ISSUE THREAD

**Issue by tdeichel** [cloudfoundry-community/jumpbox-boshrelease#38]
When attempting to update a user's public ssh key, the deployment pretends to be successful, but does not update  ~/.ssh/authorized_keys using jumpbox release 4.2.14

**Comment by deadlysyn** [comment]
Colleagues encountered this as well.  Unfortunately, I don't have the environment available to experiment with, so dug through the repo to try and understand why this happens.

The jumpbox job's ctl script just spawns a background watcher process.  That script gets built out as a template, including the ssh keys.  I'm not sure, but one theory is updates to the manifest (new keys) don't actually cause the watcher process to restart (since watcher is re-generated, not the actual ctl script)...but I am still wrapping my head around bosh jobs so this could be wrong.  :)

In #63 I made a small adjustment to watcher so it will check it's own modification time on each loop iteration and restart itself if needed.

**Comment by daviddob** [comment]
Closed via #63
